-- 테이블에 있는 데이터 수정하기

-- 기본 문법
-- UPDATE 테이블명 SET 수정할컬럼명 = 수정할값 WHERE 조건절;

-- 예시

UPDATE EMP SET SAL = 1000;

-- 복사한 테이블에서 연습하기.
-- EMP -> EMP_COPY 테이블 복사
CREATE TABLE EMP_COPY AS SELECT * FROM EMP;

SELECT * FROM EMP_COPY;

-- 전체 수정
UPDATE EMP_COPY SET SAL = 1000;
COMMIT;  --반영

-- 조건 수정
UPDATE EMP_COPY SET SAL = 2000 WHERE DEPTNO = 10;
ROLLBACK; --되돌리기

-- 서브쿼리 활용
UPDATE EMP_COPY SET SAL = 2000 
    WHERE DEPTNO = (SELECT DEPTNO FROM EMP WHERE JOB = 'ALLEN');

-- 퀴즈1) DEPT -> DEPT_TEMP2 테이블 복사해보기
--  DEPT_TEMP2 테이블에서 부서번호가 20번인 행의 지역을 'JEJU'로 수정
CREATE TABLE DEPT_TEMP2 AS SELECT * FROM DEPT;
SELECT * FROM DEPT_TEMP2;
UPDATE DEPT_TEMP2 SET LOC = 'JEJU' WHERE DEPTNO=20;
-- 퀴즈2) DEPT_TEMP2 테이블의 전체지역을 'SEOUL'로 수정
UPDATE DEPT_TEMP2 SET LOC = 'SEOUL';
-- 퀴즈3) 직책이 'MANAGER'인 사원의 급여를 5000으로 수정
-- UPDATE DEPT_TEMP2 SET SAL = 5000 WHERE JOB = 'MANAGER';

UPDATE EMP_COPY SET SAL = 5000 WHERE JOB = 'MANAGER';

-- 테이블에 있는 데이터 삭제하기

-- 조건에 맞는 데이터 삭제 (EMP테이블에서 DEPTNO=30인 행을 삭제하기.)
DELETE FROM EMP_COPY WHERE DEPTNO=30;
SELECT * FROM EMP_COPY;
-- DELETE FROM 테이블명 WHERE 조건;
-- <서브쿼리> 활용한 삭제
DELETE FROM emp_copy WHERE DEPTNO
    IN ( SELECT DEPTNO FROM DEPT WHERE LOC = 'DALLAS');

-- 테이블에 있는 모든 데이터 삭제
DELETE FROM EMP_COPY;

--서브쿼리로 'DALLAS'에 있는 부서의 사원 삭제
DELETE FROM EMP_COPY WHERE DEPTNO
    IN ( SELECT DEPTNO FROM DEPT WHERE LOC = 'DALLAS');
SELECT DEPTNO FROM DEPT WHERE LOC = 'DALLAS';

-- 퀴즈1) EMP_TEMP2 테이블에서 급여가 3000 이상인 사원 삭제
CREATE TABLE EMP_TEMP AS SELECT * FROM EMP;
SELECT * FROM EMP;
DELETE FROM EMP_TEMP2 WHERE SAL >=3000;
-- 퀴즈2)EMP_TEMP2 테이블에서 부서번호가 10 또는 20인 사원을 삭제.
DELETE FROM EMP_TEMP2 WHERE DEPTNO IN(10,20);
-- 퀴즈3) EMP_TEMP2 테이블의 모든 데이터를 삭제.
DELETE FROM EMP_TEMP2;